### PR TITLE
Remove NSError out parameters from dts

### PR DESCRIPTION
**Pull request by jasssonpet**

### CODE REVIEW

**Comment by jasssonpet** [comment]
ping @ivanbuhov @fealebenpae

**Comment by PanayotCankov** [comment]
:+1:

**Comment by jasssonpet** [comment]
Should be merged after https://github.com/NativeScript/ios-metadata-generator/pull/8 with https://github.com/NativeScript/ios-runtime/pull/208

**Comment by fealebenpae** [comment]
Can we just skip the `NSError**` parameters altogether instead of making them optional?

**Comment by jasssonpet** [comment]
This could break some existing code. I'm all up for this, but lets do it later.

**Comment by fealebenpae** [comment]
Well, yes, but at least with TypeScript it will be a compile-time error that is easy enough to amend. I'm leery of leaving the API in such a state initially. What about emitting JSDoc annotation for the optional `NSError**` parameter to mark it as deprecated and discourage its use? That way we shouldn't break existing code, and almost noone will write new code making use of the deprecated parameter after seeing the notice in the code completion popup.

**Comment by PanayotCankov** [comment]
@fealebenpae On a second thought, we can really just remove it from the d.ts. It will help the modules migrate. After all that's what TS' purpose is - making large scale refactoring easy. Using the deprecated behavior will be available by simply casting the method to &lt;any&gt; so we have TS friendly workaround.

**Comment by jasssonpet** [comment]
Should I do the same (deleting the parameter) in the current TypeScript definitions in the NativeScript repo?

**Comment by jasssonpet** [comment]
Removed `NSError`s from the current declarations.

**Pull request merged**
